import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { ConvexClientProvider } from '@/components/convex-client-provider'

import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <head>
                <script crossOrigin='anonymous' src='//unpkg.com/react-scan/dist/auto.global.js' />
            </head>
            <body className={`${inter.className}`}>
                <NuqsAdapter>
                    <ConvexClientProvider>{children}</ConvexClientProvider>
                </NuqsAdapter>
            </body>
        </html>
    )
}
